# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  # Pods for Runner
  # Use the following line to use App Center Analytics and Crashes.x
  pod 'AppCenter'
  pod 'AppCenter/Analytics'
  pod 'AppCenter/Crashes'
  pod 'AppCenter/Distribute'
  
end
